#!/bin/sh

a=10
b=20

if [ $a -eq $b ]
then
   echo "$a -eq $b : a ir vienads ar b"
else
   echo "$a -eq $b: a nav vienads ar b"
fi

if [ $a -ne $b ]
then
   echo "$a -ne $b: a nav vienads ar b"
else
   echo "$a -ne $b : a ir vienads ar b"
fi

if [ $a -gt $b ]
then
   echo "$a -gt $b: a ir lielaks par b"
else
   echo "$a -gt $b: a nav lielaks par b"
fi

if [ $a -lt $b ]
then
   echo "$a -lt $b: a ir mazaks par b"
else
   echo "$a -lt $b: a nav mazaks par b"
fi

if [ $a -ge $b ]
then
   echo "$a -ge $b: a ir lielaks par b vai vienads ar b"
else
   echo "$a -ge $b: a nav lielaks par b vai vienads ar b"
fi

if [ $a -le $b ]
then
   echo "$a -le $b: a ir mazaks par b vai vienads ar b"
else
   echo "$a -le $b: a nav mazaks par b vai vienads ar b"
fi
